sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
  - 8.11.4
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install -g typescript
  - npm install -g protractor
  - webdriver-manager update
  - webdriver-manager --detach start
script:
  - tsc
  - npm run test