sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: "56.0"
  apt:
    packages:
    - chromium-chromedriver
language: node_js
node_js:
  - 8.11.4
cache:
  directories:
  - node_modules
before_install:
 - sudo apt-get install xvfb
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
install:
- npm install
- npm install -g typescript
- npm install -g protractor
- webdriver-manager update
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - webdriver-manager --detach start
script:
  - tsc
  - npm test