sudo: required
dist: trusty
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
    - chromium-chromedriver
language: node_js
node_js:
  - 8.11.4
cache:
  directories:
  - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - webdriver-manager --detach start
install:
  - npm install
  - npm install -g typescript
  - npm install -g protractor
  - webdriver-manager update
script:
  - tsc
  - npm test