sudo: required
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
    - chromium-chromedriver
language: node_js
node_js:
  - 8.11.4
cache:
  directories:
  - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
install:
  - npm install
  - npm install -g typescript
  - npm install -g protractor
  - webdriver-manager update
  - webdriver-manager --detach start
script:
  - tsc
  - npm run test